package bankidl.BankPackage;

/**
* bankidl/BankPackage/rejectedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Sunday, November 15, 2015 2:40:20 PM CET
*/

public final class rejectedHolder implements org.omg.CORBA.portable.Streamable
{
  public bankidl.BankPackage.rejected value = null;

  public rejectedHolder ()
  {
  }

  public rejectedHolder (bankidl.BankPackage.rejected initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = bankidl.BankPackage.rejectedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    bankidl.BankPackage.rejectedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return bankidl.BankPackage.rejectedHelper.type ();
  }

}
