package bankidl.BankPackage;


/**
* bankidl/BankPackage/rejected.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Sunday, November 15, 2015 2:40:20 PM CET
*/

public final class rejected extends org.omg.CORBA.UserException
{
  public String reason = null;

  public rejected ()
  {
    super(rejectedHelper.id());
  } // ctor

  public rejected (String _reason)
  {
    super(rejectedHelper.id());
    reason = _reason;
  } // ctor


  public rejected (String $reason, String _reason)
  {
    super(rejectedHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class rejected
