package bankidl.AccountPackage;

/**
* bankidl/AccountPackage/rejectedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Sunday, November 15, 2015 2:40:20 PM CET
*/

public final class rejectedHolder implements org.omg.CORBA.portable.Streamable
{
  public bankidl.AccountPackage.rejected value = null;

  public rejectedHolder ()
  {
  }

  public rejectedHolder (bankidl.AccountPackage.rejected initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = bankidl.AccountPackage.rejectedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    bankidl.AccountPackage.rejectedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return bankidl.AccountPackage.rejectedHelper.type ();
  }

}
