package bankidl;


/**
* bankidl/_AccountImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Sunday, November 15, 2015 2:40:20 PM CET
*/

public abstract class _AccountImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements bankidl.Account, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _AccountImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_balance", new java.lang.Integer (0));
    _methods.put ("deposit", new java.lang.Integer (1));
    _methods.put ("withdraw", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // bankidl/Account/_get_balance
       {
         float $result = (float)0;
         $result = this.balance ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 1:  // bankidl/Account/deposit
       {
         try {
           float value = in.read_float ();
           this.deposit (value);
           out = $rh.createReply();
         } catch (bankidl.AccountPackage.rejected $ex) {
           out = $rh.createExceptionReply ();
           bankidl.AccountPackage.rejectedHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // bankidl/Account/withdraw
       {
         try {
           float value = in.read_float ();
           this.withdraw (value);
           out = $rh.createReply();
         } catch (bankidl.AccountPackage.rejected $ex) {
           out = $rh.createExceptionReply ();
           bankidl.AccountPackage.rejectedHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:bankidl/Account:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _AccountImplBase
