package bankidl;


/**
* bankidl/_BankImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Sunday, November 15, 2015 2:40:20 PM CET
*/

public abstract class _BankImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements bankidl.Bank, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _BankImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("newAccount", new java.lang.Integer (0));
    _methods.put ("getAccount", new java.lang.Integer (1));
    _methods.put ("deleteAccount", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // bankidl/Bank/newAccount
       {
         try {
           String name = in.read_string ();
           bankidl.Account $result = null;
           $result = this.newAccount (name);
           out = $rh.createReply();
           bankidl.AccountHelper.write (out, $result);
         } catch (bankidl.BankPackage.rejected $ex) {
           out = $rh.createExceptionReply ();
           bankidl.BankPackage.rejectedHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // bankidl/Bank/getAccount
       {
         String name = in.read_string ();
         bankidl.Account $result = null;
         $result = this.getAccount (name);
         out = $rh.createReply();
         bankidl.AccountHelper.write (out, $result);
         break;
       }

       case 2:  // bankidl/Bank/deleteAccount
       {
         String acc = in.read_string ();
         boolean $result = false;
         $result = this.deleteAccount (acc);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:bankidl/Bank:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _BankImplBase
