package bankidl;

/**
* bankidl/AccountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Sunday, November 15, 2015 2:40:20 PM CET
*/

public final class AccountHolder implements org.omg.CORBA.portable.Streamable
{
  public bankidl.Account value = null;

  public AccountHolder ()
  {
  }

  public AccountHolder (bankidl.Account initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = bankidl.AccountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    bankidl.AccountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return bankidl.AccountHelper.type ();
  }

}
