package bankidl;


/**
* bankidl/AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Sunday, November 15, 2015 2:40:20 PM CET
*/

public interface AccountOperations 
{
  float balance ();
  void deposit (float value) throws bankidl.AccountPackage.rejected;
  void withdraw (float value) throws bankidl.AccountPackage.rejected;
} // interface AccountOperations
