package bankidl;

/**
* bankidl/BankHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Sunday, November 15, 2015 2:40:20 PM CET
*/

public final class BankHolder implements org.omg.CORBA.portable.Streamable
{
  public bankidl.Bank value = null;

  public BankHolder ()
  {
  }

  public BankHolder (bankidl.Bank initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = bankidl.BankHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    bankidl.BankHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return bankidl.BankHelper.type ();
  }

}
