package bankidl;


/**
* bankidl/BankOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Sunday, November 15, 2015 2:40:20 PM CET
*/

public interface BankOperations 
{
  bankidl.Account newAccount (String name) throws bankidl.BankPackage.rejected;
  bankidl.Account getAccount (String name);
  boolean deleteAccount (String acc);
} // interface BankOperations
