package bankidl;


/**
* bankidl/Bank.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Sunday, November 15, 2015 2:40:20 PM CET
*/

public interface Bank extends BankOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Bank
